### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by jtal** [eliostvs/tomate#1]
Is Tomate ready to use? I see a bunch of python scripts. Do I execute one to start the app?

**Comment by serkandurusoy** [comment]
Yep, I'm on ubuntu 14.04 64-bit and there is no evidence of a launcher for this, not in dash, not on launcher, no tomate or pyhton-tomate command on terminal.

So what do we do after the install?

**Comment by eliostvs** [comment]
Sorry for the delay in answering. Tomate is just the library. You should install the gui and maybe the plugins. They are:

- [tomate-gtk](https://github.com/eliostvs/tomate-gtk)
- [tomate-notify-plugin](https://github.com/eliostvs/tomate-notify-plugin)
- [tomate-launcher-plugin](https://github.com/eliostvs/tomate-launcher-plugin) (Ubuntu/Unity only)
- [tomate-alarm-plugin](https://github.com/eliostvs/tomate-alarm-plugin)
- [tomate-notify-plugin](https://github.com/eliostvs/tomate-notify-plugin)
- [tomate-indicator-plugin](https://github.com/eliostvs/tomate-indicator-plugin)

In Ubuntu use the following command to install:

    sudo apt-get install tomate-gtk tomate-notify-plugin tomate-alarm-plugin tomate-launcher-plugin tomate-indicator-plugin

You can enable a plugin through the preferences dialog:
![Here](http://i.imgur.com/XWtcgga.png)

**Comment by serkandurusoy** [comment]
Oh! Thank you for this info. Perhaps you may want to update the readme.

Also, for example, for intallation on ubuntu, do we need to install python-tomate or does it get implicitely installed by installing tomate-gtk and pugins?

**Comment by eliostvs** [comment]
Hi. I definitely have to write a better readme. But I wanna do some big changes in the code before. 

All plugins depends on tomate-gtk, and tomate-gtk depends on python-tomate. So you just need to install one plugin to get the whole package.

**Comment by serkandurusoy** [comment]
Great! Thank you.
