### ISSUE TITLE
indicator does not show up

### ISSUE THREAD

**Issue by lutostag** [eliostvs/tomate#11]
I cannot get the indicator to show up. (yes it is enabled in extensions and the notify one works just fine).

I'm on ubuntu 15.10. With installed versions from the repository:
ii  python-tomate                                 0.3.0                                      all
A pomodoro timer. Core classes.                                                                 
ii  tomate-gtk                                    0.3.0                                      all
Gtk version from Tomate pomodoro timer.                                                         
ii  tomate-indicator-plugin                       0.3.0                                      all
Tomate plugin that shows the session progress in indicator.                                     
ii  tomate-notify-plugin                          0.3.0                                      all
Tomate plugin that shows screen notifications.                                                  

I am available to debug, anything I can do to help resolve this issue.

Thanks.

**Comment by paulrd** [comment]
For me the the indicator only shows up if you 'close' the app via the 'x' in the top left corner.

**Comment by lutostag** [comment]
Hmm, doesn't work for me. When I close tomate via the standard window controls the process exits. Thanks for your experience. I'll try to dive into the code sometime over the weekend to hopefully see what is happening.

I actually did get the indicator to show up by just hitting ctrl-c on the program at some random time, but was unable to reproduce, so there appears to be some hope for me.

**Comment by shookees** [comment]
Could you try running `tomate-gtk -v` with verbose flag, try running the following test case:
1. Open plugin window, toggle twice the plugin checkbox (if turned on, turn off and then on and vice versa)
2. With plugin turned on, try running a pomodoro/break timer and then closing the window.

**Comment by lutostag** [comment]
Ah, seems like I totally didn't understand how that plugin was being used. It works as you have laid out just fine -- just contrary to my expectations (since the previous launchpad iteration always had the indicator visible iirc).

inline diff for hacky version of what I was expecting (against packaged version 0.3.0 of tomate_gtk/indicator.py):

53a54
>         self.show()
62c63
<         self.indicator.set_status(AppIndicator3.IndicatorStatus.PASSIVE)
---
>         self.indicator.set_status(AppIndicator3.IndicatorStatus.ACTIVE)

Attaching the log -- [log.txt](https://github.com/eliostvs/tomate/files/101177/log.txt), but it seems superfluous after all.
Thanks for the help everybody! Sorry for the confusion.
