### ISSUE TITLE
Linux Mint 18

### ISSUE THREAD

**Issue by bmcfarlin** [eliostvs/tomate#12]
Would you please make the Linux Mint 18 version available in the repository?  I'm not able to build from source.

**Comment by eliostvs** [comment]
Hi,

I'm going to do some tests but it  may work if you configure as a equivalent [Ubuntu](https://github.com/eliostvs/tomate-gtk#ubuntu-1404) version.

**Comment by eliostvs** [comment]
Hi,

I did some tests with Linux Mint 18 and you should follow the [ubuntu installation guide](https://github.com/eliostvs/tomate-gtk#ubuntu-1404) but the version has to be 14.04. Cheers.
