### ISSUE TITLE
Missing 'dbus.session' dependency

### ISSUE THREAD

**Issue by ok2cqr** [eliostvs/tomate#13]
I got this error after installing tomato-gtk, tomate-alarm-plugin, tomate-indicator-plugin and tomate-launcher-plugin. I tried to uninstall plugins but still the same error. Python-dbus is installed.

ERROR:2016-10-02 16:21:19,070:tomate_gtk.main:Cannot find dependency u'dbus.session' for u'tomate.app' provider.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tomate_gtk/main.py", line 64, in main
    graph.validate()
  File "/usr/lib/python2.7/dist-packages/wiring/graph.py", line 356, in validate
    strongconnect(specification)
  File "/usr/lib/python2.7/dist-packages/wiring/graph.py", line 328, in strongconnect
    raise MissingDependencyError(specification, dependency)
MissingDependencyError: Cannot find dependency u'dbus.session' for u'tomate.app' provider.
Traceback (most recent call last):
  File "/usr/bin/tomate-gtk", line 9, in <module>
    load_entry_point('tomate-gtk==0.6.0', 'console_scripts', 'tomate-gtk')()
  File "/usr/lib/python2.7/dist-packages/tomate_gtk/main.py", line 74, in main
    six.reraise(*sys.exc_info())
  File "/usr/lib/python2.7/dist-packages/tomate_gtk/main.py", line 64, in main
    graph.validate()
  File "/usr/lib/python2.7/dist-packages/wiring/graph.py", line 356, in validate
    strongconnect(specification)
  File "/usr/lib/python2.7/dist-packages/wiring/graph.py", line 328, in strongconnect
    raise MissingDependencyError(specification, dependency)
wiring.graph.MissingDependencyError: Cannot find dependency u'dbus.session' for u'tomate.app' provider.

Ubuntu 16.04 64bit here.
Linux neptun 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Do you know where could be the problem, please?

**Comment by eliostvs** [comment]
Hi, `python-tomate` is a dependency for `tomate-gtk`, it should be installed automatically with `tomate-gtk`. Could you if `phton-tomate` is installed? Ex: ```dpkg -l | grep python-tomate```

**Comment by eliostvs** [comment]
Hi. Do you still have this problem? Cheers.

**Comment by ImpracticalDogg** [comment]
Hi, I have updated and this problem has just come up.  Ubuntu 16.04 64-bit.  

The app was running fine, but now will not start.  Output of dpkg below:

dpkg -l | grep python-tomate
ii  python-tomate                               0.6.0                                         all          A pomodoro timer. Core classes.

**Comment by ImpracticalDogg** [comment]
OK, I rebooted and now everything works.  The app had disappeared from my desktop, so I wanted to restart it.  I think it was running in the background previously, because when I logged in again and it started up I tried to run another instance from the terminal.  The exact same errors came up again.

**Comment by eliostvs** [comment]
I think I've found the problem. The version 0.7.0 still broken. I will release a new version in the next days.

**Comment by eliostvs** [comment]
I you still have problems, please open a new issue.
