### ISSUE TITLE
Installing problems on Ubuntu - trying to overwrite '/usr/lib/python2.7/dist-packages/tomate/__init__.py

### ISSUE THREAD

**Issue by surfnet-niels** [eliostvs/tomate#2]
Hi,

I want to install tomate using apt on Ubuntu 14.04 as described here:
https://github.com/eliostvs/tomate/blob/master/README.md

Upon install I get:
Reading state information... Done
The following NEW packages will be installed:
  python-tomate
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
13 not fully installed or removed.
Need to get 0 B/6932 B of archives.
After this operation, 66,6 kB of additional disk space will be used.
(Reading database ... 395286 files and directories currently installed.)
Preparing to unpack .../python-tomate_0.3.0_all.deb ...
Unpacking python-tomate (0.3.0) ...
dpkg: error processing archive /var/cache/apt/archives/python-tomate_0.3.0_all.deb (--unpack):
 trying to overwrite '/usr/lib/python2.7/dist-packages/tomate/__init__.py', which is also in package tomate 0.3.1-0+14+201402022216~ubuntu13.10.1
Errors were encountered while processing:
 /var/cache/apt/archives/python-tomate_0.3.0_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Manually removing the file does not work.
Any suggestions?

**Comment by eliostvs** [comment]
Hi. Sorry for the delay. I've installed in a ubuntu:14.04 container (docker) and it worked normally. Try to clean yours cache and install the package again. Example:

`sudo apt-get clean && sudo apt-get install python-tomate`

You still have to install the [gui](https://github.com/eliostvs/tomate-gtk) and plugins.

If you still have problems, let me know. Best regards.

**Comment by sebix** [comment]
> Manually removing the file does not work.
How did you try to remove the file?

**Comment by eliostvs** [comment]
I've used a clean installation of the Ubuntu. Do you have a old version of
Tomate?

**Comment by swillner** [comment]
I had the same problem, because I still had the old(?) http://ppa.launchpad.net/stvs/tomate/ubuntu - repository and package "tomate" installed. Just removing package "tomate" should fix your problem.

**Comment by eliostvs** [comment]
I'm updating the docs. If you still have a problem let me know.
