### ISSUE TITLE
documentation: installation incomplete?

### ISSUE THREAD

**Issue by cpbl** [eliostvs/tomate#3]
The README.me file on Ubuntu says only to install python-tomate

This left me (in 15.04) without any tomate-related executable on my path.

But installing tomate-gtk

(or all of "sudo apt-get install tomate-gtk tomate-notify-plugin tomate-alarm-plugin tomate-launcher-plugin tomate-indicator-plugin")

left me with a fully-functioning tomate-gtk

**Comment by orschiro** [comment]
I can confirm what @cpbl said. You need to install the other packages as well to have a working installation on Ubuntu 15.04. 

I will create a pull request for this. 

Thanks for your work!

**Comment by orschiro** [comment]
https://github.com/eliostvs/tomate/pull/5

**Comment by eliostvs** [comment]
Thanks! I'm updating the docs.

**Comment by orschiro** [comment]
@eliostvs 

Great, thank you! :+1: 

~ Robert
