### ISSUE TITLE
Won't start 

### ISSUE THREAD

**Issue by vuemaster** [eliostvs/tomate#4]
Hello, I installed with sudo python setup.py install and it went through, without a problem, then I tried to execute it (debian) and it says:

`Traceback (most recent call last):
  File "/usr/local/bin/tomate", line 47, in <module>
    tomate.main()
AttributeError: 'module' object has no attribute 'main'`

Is there an easy solution for that problem?

all the best

**Comment by eliostvs** [comment]
Hello. Are you using Debian 8? Try to use the repository:

```
RELEASE=8.0
sudo wget -O- http://download.opensuse.org/repositories/home:/eliostvs:/tomate/Debian_$RELEASE/Release.key | sudo apt-key add -
sudo bash -c "echo 'deb http://download.opensuse.org/repositories/home:/eliostvs:/tomate/Debian_$RELEASE/ ./' > /etc/apt/sources.list.d/tomate.list"
sudo apt-get update && sudo apt-get install tomate-gtk
```

**Comment by eliostvs** [comment]
I'm updating the docs. If you still have problem let me know.
