### ISSUE TITLE
New feature: Lock or black screen during break

### ISSUE THREAD

**Issue by orschiro** [eliostvs/tomate#7]
Dear all, 

What do you think of a new feature that blacks or locks the screen during the break time?

This would be a "subtle" enforcement to really take a break for users who are too avid to continue otherwise. :)

~ Robert

**Comment by shookees** [comment]
Sounds like a nice plugin. The only question figuring on how to emulate the locking process or retrieve the required things/services for locking the desktop.

**Comment by orschiro** [comment]
@shookees,

Maybe we can take some inspiration for the locking mechanism from this project: 

http://askubuntu.com/questions/696620/a-timer-that-automatically-locks-the-screen-to-take-a-break-away-from-the-comput

Warmly,

~ Robert

**Comment by sebix** [comment]
Workrave for example has an optional blocking possibility for breaks. https://github.com/rcaelers/workrave

**Comment by shookees** [comment]
Well, found out locking the screen is easy afterall:
`xdg-screensaver lock` does the job, thus a simple plugin should do this. Would also be intersesting to see whether the unity lock screen has some kind of API to display arbitrary modals and thus be able to show the break from work timer.
I'm investigating the following issue

**Comment by orschiro** [comment]
Great, thank you @shookees for following up on this feature!

-Robert

**Comment by bartekbrak** [comment]
I really wanted that feature so I started developing it but spent 90% of the time in setting up development environment for this package (@eliostvs, please document it somehow, pretty please, :), see https://github.com/bartekbrak/tomate-gtk/commit/2c26d01507b8eebf608aa40ca9d852e55eb4ada3 as a start) and didn't have time to actually do the work, or package it so I went the quick and dirty way. Sharing so that you may also use it:

1. Install tomato version 0.6.0 (or any that uses plugins), in Ubuntu 14.04 this means adding PPA.
2. `apt install tomate-alarm-plugin`
3. sudo patch -u /usr/share/tomate/plugins/alarm_plugin.py alarm_plugin_dims_screen.diff

`alarm_plugin_dims_screen.diff`:
```
diff --git a/data/plugins/alarm_plugin.py b/data/plugins/alarm_plugin.py
index 593f611..dda06ce 100644
--- a/data/plugins/alarm_plugin.py
+++ b/data/plugins/alarm_plugin.py
@@ -13,6 +13,7 @@ from tomate.constant import State
 from tomate.event import Events, on
 from tomate.graph import graph
 from tomate.utils import suppress_errors
+import re, subprocess
 
 
 logger = logging.getLogger(__name__)
@@ -39,9 +40,25 @@ class AlarmPlugin(tomate.plugin.Plugin):
     @on(Events.Session, [State.finished])
     def ring(self, *args, **kwargs):
         self.player.set_state(Gst.State.PLAYING)
-
         logger.debug('play ')
 
+    @on(Events.Session, [State.started])
+    def bright(self, *args, **kwargs):
+        self._dim(1)
+
+    @on(Events.Session, [State.finished, State.stopped])
+    def dim(self, *args, **kwargs):
+        self._dim(0.2)
+
+    def _dim(self, value):
+        screens = re.findall('(\w+) connected', subprocess.check_output(["xrandr"]).decode("utf-8"))
+        logger.debug('screens found: %s' % screens)
+        for screen in screens:
+            cmd = 'xrandr --output %s --brightness %.1f' % (screen, value)
+            logger.debug('calls: %s' % cmd)
+            subprocess.call(cmd.split())
+
+
     @suppress_errors
     def on_message(self, bus, message):
         if message.type == Gst.MessageType.EOS:
```

**Comment by eliostvs** [comment]
Hi, thanks for the contribution. You can have your own plugins. Just put the py module inside the directory *~/.local/share/tomate/plugins/*  and create a metadata file, for example the [alarm plugin metadata](https://raw.githubusercontent.com/eliostvs/tomate-alarm-plugin/master/data/plugins/alarm.plugin).

**Comment by eliostvs** [comment]
Hi, I finally create a official plugin [breakscreen-plugin](https://github.com/eliostvs/tomate-breakscreen-plugin). I'll archive this repository soon. We can keep this discussion in the plugin repository.
