### ISSUE TITLE
Failed installation of tomate-gtk on Ubuntu 15.10 (Wily)

### ISSUE THREAD

**Issue by squidsoup** [eliostvs/tomate#8]
Installation invoked with `sudo apt-get update && sudo apt-get install python-tomate tomate-gtk tomate-notify-plugin tomate-alarm-plugin tomate-launcher-plugin tomate-indicator-plugin` fails on Ubuntu 15.10.
   
    Unpacking tomate-gtk (0.3.0) ...
    dpkg: error processing archive /var/cache/apt/archives/tomate-gtk_0.3.0_all.deb (--unpack):
     trying to overwrite '/usr/lib/python2.7/dist-packages/tests/__init__.py', which is also in package python-     codetree 0.0.3-3
    dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)

**Comment by eliostvs** [comment]
Have you installed a previous version from the old ppa repository? Please uninstall the old version first. I've added the Ubuntu 15.10 repository and I'm updating the installation docs.
